image: python:3.6

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - pip install spiceypy --no-cache-dir
  - python setup.py test
